QPID-6690: Set exception on ListenableFuture on Errors like NoClassDefFoundError in order to interrupt unlimited get            Change RestServlet to return an error response instead of 500 on NoClassDefFoundError
git-svn-id: https://svn.apache.org/repos/asf/qpid/java/trunk@1695444 13f79535-47bb-0310-9956-ffa450edef68